image: node

stages:
  - deploy
  - test

deploy to vercel:
  stage: deploy
  script:
    - npm install
    - npm i -g @angular/ci
    - echo $DEPLOYMENT_URL$(vercel -t $VERCEL_TOKEN --confirm)

  artifacts:
    when: on_success
    paths:
      - vercel_deployment_url.txt

cypress test:
  image: cypress/browsers:node12.16.2-chrome81-ff75
  stage: test

  script:
    - DEPLOYMENT_URL=$(cat vercel_deployment_url.txt)
    - npm ci
    - $(npm bin)/cypress run --env CYPRESS_BASE_URL=$DEPLOYMENT_URL

  artifacts:
    when: on_success
    paths:
      - cypress/screenshots
      - cypress/videos
