image: node:16

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production tests

variables:
  STAGING_DOMAIN: next-staging.surge.sh
  PRODUCTION_DOMAIN: next-basket.surge.sh

cache:
  key: $CI_COMMIT_SHORT_SHA
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm i @angular/cli
    - npm run build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./dist/tabaka-hos/index.html
    - ls

  artifacts:
    paths:
      - ./src
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Tabaka" ./src/index.html

test website:
  stage: test
  script:
    - npm install
    - npm i @angular/cli
    - npm run start &
    - sleep 30
    - curl "http://localhost:4200/" | tac | tac | grep -q "Tabaka"

deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  only:
    - master
  script:
    - npm install --global surge
    - npm run build
    - sleep 30
    - surge --project ./dist/tabaka-hos --domain next-staging.surge.sh

deploy production:
  stage: deploy production
  environment:
    name: staging
    url: http://$PRODUCTION_DOMAIN
  only:
    - master
  script:
    - npm install --global surge
    - npm run build
    - sleep 30
    - ls
    - surge --project ./dist/tabaka-hos --domain next-basket.surge.sh

production tests:
  image: alpine
  stage: production tests
  only:
    - master
  script:
    - apk add --no-cache curl
    - curl -s "https://next-basket.surge.sh/" | grep -q "Tabaka"
    - curl -s "https://next-basket.surge.sh/" | grep -q "$CI_COMMIT_SHORT_SHA"
