stages:
  - build
  - test

build website:
  stage: build
  image: node:16
  script:
    - npm install
    - npm i @angular/cli
    - npm run build

  artifacts:
    paths:
      - ./src
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Tabaka" ./src/index.html

test website:
  ima
  stage: test
  script:
    - npm install
    - npm i @angular/cli
    - ng serve
    - curl "http://localhost:4200" | grep -q "Tabaka"
    - npm run start &
    - sleep 30
    - curl "http://localhost:4200/" | tac | tac | grep -q "Tabaka"


deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./src --domain next-basket.surge.sh

