stages:
  - build
  - test

build website:
  stage: build
  image: node:16
  script:
    - npm install
    - npm i @angular/cli
    - npm run build

  artifacts:
    paths:
      - ./src
test artifact:
  stage: test
  script:
    - grep "Tabaka" ./src/index.html
    - grep "Oluoch" ./src/index.html
