stages:
  - build
  - test

build website:
  stage: build
  image: node:16
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm i @angular/cli
    - npm run build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./src/index.html

  artifacts:
    paths:
      - ./src
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Tabaka" ./src/index.html

test website:
  ima
  stage: test
  script:
    - npm install
    - npm i @angular/cli
    - ng serve
    - curl "http://localhost:4200" | grep -q "Tabaka"
    -
