image: node:16

stages:
  - build
  - test
  - deploy
  - deployment test

cache:
  key: $CI_COMMIT_SHORT_SHA
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm i @angular/cli
    - npm run build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./src/index.html

  artifacts:
    paths:
      - ./src
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Tabaka" ./src/index.html

test website:
  stage: test
  script:
    - npm install
    - npm i @angular/cli
    - npm run start &
    - sleep 30
    - curl "http://localhost:4200/" | tac | tac | grep -q "Tabaka"

deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - ls
    - surge --project ./src --domain next-basket.surge.sh

test deployment:
  image: alpine
  stage: deployment test
  script:
    - apk add --no-cache curl
    - curl -s "https://next-basket.surge.sh/" | grep -q "Tabaka"
    - curl -s "https://next-basket.surge.sh/" | grep -q "$CI_COMMIT_SHORT_SHA"
