image: node:16

stages:
  - build
  - test

build website:
  stage: build
  except:
    - schedules
  only:
    - master
    - merge_requests
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g @angular/cli
    - npm run build
    - ls
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./src/index.html

  artifacts:
    paths:
      - ./dist/tabaka-hos


test artifacts:
  image: alpine
  stage: test
  cache: {}
  except:
    - schedules
    only:
      - master
      - merge_requests
  script:
    - grep -g 'Tabaka' ./dist/yabaka-hos/index.html


